FROM apache/airflow:2.10.0-python3.12

USER airflow

RUN pip install --no-cache-dir \
    mlflow==2.22.0 \
    scikit-learn \
    pandas \
    numpy \
    matplotlib \
    seaborn \
    tqdm \
    psycopg2-binary \
    requests